"use strict";//  P A C K A G E
const chronverRegex=require("chronver-regex"),MAX_LENGTH=256,MAX_SAFE_INTEGER=Number.MAX_SAFE_INTEGER||9007199254740991;//  U T I L S
exports=module.exports=ChronVer,exports.coerce=coerce,exports.increment=increment,exports.initialize=initialize,exports.parse=parse,exports.valid=valid;//  P R O G R A M
function ChronVer(a){if(a instanceof ChronVer&&(a=a.version),"string"!=typeof a)throw new TypeError(`Invalid version: ${a}`);if(a.length>MAX_LENGTH)throw new TypeError(`Version is longer than ${MAX_LENGTH} characters`);if(!(this instanceof ChronVer))return new ChronVer(a);this.raw=a;const b=a.trim().match(chronverRegex())?// $FlowFixMe: I have no idea how to make Flow like this line
a.trim().match(chronverRegex())[0].split("."):null;if(!b)return b;if(this.year=+b[0],this.month=+b[1],this.day=+b[2],this.change=b[3]?+b[3]||b[3]+a.split(b[3])[1]+"":0,this.year>MAX_SAFE_INTEGER||0>this.year)throw new TypeError("Invalid year version");if(this.month>MAX_SAFE_INTEGER||0>this.month)throw new TypeError("Invalid month version");if(this.day>MAX_SAFE_INTEGER||0>this.day)throw new TypeError("Invalid day version");if(+this.change>MAX_SAFE_INTEGER||0>+this.change)throw new TypeError("Invalid change version");return this._format()}ChronVer.prototype._format=function(){return this.version=this.year+"."+processMonth(this.month)+"."+processDay(this.day)+processChange(this.change),this.version},ChronVer.prototype.coerce=function(a){return coerce(a)},ChronVer.prototype.increment=function(a){switch(!0){// Supplied year is less than current year
// Supplied year is current but supplied month is less than current month
// Supplied year and month are current but supplied day is less than current day
case this.year<+new Date().getFullYear():case this.year===+new Date().getFullYear()&&this.month<+new Date().getMonth()+1:case this.year===+new Date().getFullYear()&&this.month===+new Date().getMonth()+1&&this.day<+new Date().getDate():return initialize();// Update old version to present
default:}switch(a){case"day":this.day++;break;case"month":this.month++;break;case"year":this.year++;break;default:case"change":"number"==typeof this.change&&this.change++;}return this._format(),this.raw=this.version,this},ChronVer.prototype.initialize=function(){return initialize()};//  H E L P E R S
function coerce(a){if(a instanceof ChronVer)return a;if("number"==typeof a&&(a+=""),"string"!=typeof a)return null;const b=a.trim().split(".");let c=+b[0],d=+b[1],e=+b[2];return(c>MAX_SAFE_INTEGER||0>c)&&(c=new Date().getFullYear()+""),(d>MAX_SAFE_INTEGER||0>d||12<d)&&(d=new Date().getMonth()+1+""),(e>MAX_SAFE_INTEGER||0>e||31<e)&&(e=new Date().getDate()+""),new ChronVer(`${c}.${processMonth(d)}.${processDay(e)}`)}function increment(a,b){try{return new ChronVer(a).increment(b).version}catch(a){return null}}function initialize(){const a=+new Date().getFullYear(),b=processMonth(+new Date().getMonth()+1),c=processDay(+new Date().getDate());return new ChronVer(`${a}.${b}.${c}`)}function parse(a){if(a instanceof ChronVer)return a;if("string"!=typeof a)return null;if(a.length>MAX_LENGTH)return null;if(!chronverRegex().test(a))return null;try{return new ChronVer(a)}catch(a){return null}}function processChange(a){return"number"==typeof a&&0===a?"":0<(a+"").length?"."+a:""}function processDay(a){return 0==+a&&(a=1),1<(a+"").length?a:"0"+a}function processMonth(a){return 0==+a&&(a=1),1<(a+"").length?a:"0"+a}function valid(a){const b=parse(a);return b?b.version:null}